<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>es6-proxy</title>
    <script src="bin/traceur.js" type="text/javascript"></script>
    <script src="bin/bootstrap.js" type="text/javascript"></script>
</head>
<body>
<script type="module">
    //异步加载图片的例
    function loadImageAsync(url) {
        return new Promise(function(resolve, reject) {
            var image = new Image();
            image.onload = function() {
                resolve(image);
            };
            image.onerror = function() {
                reject(new Error('Could not load image at ' + url));
            };
            image.src = url;
        });
    }
    loadImageAsync('http://imge.kugou.com/commendpic/20140812/20140812150403118306.jpg').then(function(){
        console.log("加载完成！");
    }).catch(function(error){
        console.error('出错了',error);
    })

    //下面是一个用Promise对象实现的Ajax操作的例子
    var getJSON = function(url) {
        var promise = new Promise(function(resolve, reject){
            var client = new XMLHttpRequest();
            client.open("GET", url);
            client.onreadystatechange = function(){
                if ( this.readyState === 4 ) {
                    if (this.status === 200) {
                        resolve(this.response);
                    } else {
                        reject(new Error(this.statusText));
                    }
                }
            };
            client.responseType = "json";
            client.setRequestHeader("Accept", "application/json");
            client.send();
        });
        return promise;
    };
    getJSON("./json1.json").then(function(json) {
        console.log('Contents: ', json);
    }, function(err) {
        console.error('出错了', err);
    });

    //============================扩展done()
    //Promise对象的回调链，不管以then方法或catch方法结尾，要是最后一个方法抛出错误，都有可能无法捕捉到（因为Promise内部的错误不会冒泡到全局）。
    //因此，我们可以提供一个done方法，总是处于回调链的尾端，保证抛出任何可能出现的错误。
    Promise.prototype.done = function (onFulfilled, onRejected) {
        this.then(onFulfilled, onRejected).catch(function (reason) {
            setTimeout(() => { throw reason }, 0);// 抛出一个全局错误
        });
    };
    //使用示例
    asyncFunc()
            .then(f1)
            .catch(r1)
            .then(f2)
            .done();

    //============================扩展finally()
    //finally方法用于指定不管Promise对象最后状态如何，都会执行的操作。
    //它与done方法的最大区别，它接受一个普通的回调函数作为参数，该函数不管怎样都必须执行。
    Promise.prototype.finally = function (callback) {
        let P = this.constructor;
        return this.then(
                value  => P.resolve(callback()).then(() => value),
                reason => P.resolve(callback()).then(() => { throw reason })
        );
    };
</script>
</body>
</html>